# Generated by Django 3.0.7 on 2020-07-14 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20200713_1006'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recommentlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='recommentlike',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='recommentlike',
            name='recomment',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
        migrations.DeleteModel(
            name='ReCommentLike',
        ),
    ]
