# Generated by Django 3.0.7 on 2020-07-18 12:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_auto_20200718_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(0)),
            preserve_default=False,
        ),
    ]
