# Generated by Django 3.0.7 on 2020-07-28 02:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0005_auto_20200727_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=5)),
        ),
    ]
