# Generated by Django 3.0.7 on 2020-07-28 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0006_auto_20200728_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='duration',
            field=models.DurationField(),
        ),
    ]
