# Generated by Django 3.0.7 on 2020-07-14 06:13

from django.db import migrations
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200713_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created'),
        ),
    ]
