# Generated by Django 3.0.7 on 2020-07-08 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contents',
            field=models.TextField(default=''),
        ),
    ]
