# Generated by Django 3.0.7 on 2020-07-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20200723_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
