# Generated by Django 3.0.7 on 2020-07-17 13:26

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(upload_to=users.models.profile_img_path),
        ),
    ]
