# Generated by Django 3.0.7 on 2020-07-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200706_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='relations',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.CharField(default='', max_length=300),
        ),
    ]
