# Generated by Django 3.0.7 on 2020-07-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200706_0644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='relations',
        ),
    ]
