# Generated by Django 3.0.7 on 2020-07-17 01:34

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import stories.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to=stories.models.story_img_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
